apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../../base/load-generator-python

patchesStrategicMerge:
  - patches.yaml

commonLabels:
  environment: production

images:
  - name: load-generator-python-image
    newName: <ECR_ACCOUNT_ID>.dkr.ecr.ap-southeast-1.amazonaws.com/generic-gha/load-generator-python
    newTag: latest
