apiVersion: v1
kind: Service
metadata:
  name: client-react
  namespace: staging
  labels:
    app: client-react
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: client-react
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: None
