apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../../base/api-golang

patchesStrategicMerge:
  - patches.yaml

commonLabels:
  environment: staging

images:
  - name: api-golang-image
    newName: <ECR_ACCOUNT_ID>.dkr.ecr.ap-southeast-1.amazonaws.com/generic-gha/api-golang
    newTag: 1.3.3-0019-g89447fe
