apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../../base/load-generator-python

patchesStrategicMerge:
  - patches.yaml

commonLabels:
  environment: staging

images:
  - name: load-generator-python-image
    newName: 382027875658.dkr.ecr.ap-southeast-1.amazonaws.com/generic-gha/load-generator-python
    newTag: 1.1.0-0038-g851e966
