apiVersion: v1
kind: Service
metadata:
  name: api-golang
  namespace: staging
  labels:
    app: api-golang
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: api-golang
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: None
