version: "3"

tasks:
  run:
    desc: "Run update-gitops-manifests workflow"
    dir: "../../.."
    cmds:
      - |
        act workflow_dispatch \
          --container-architecture linux/arm64 \
          --eventpath .github/workflows/update-gitops-manifests/event.json \
          --workflows .github/workflows/update-gitops-manifests.yaml \
          --cache-server-path ~/.cache/act
