version: "3"

tasks:
  run:
    desc: "Hello world"
    dir: "../../.."
    cmds:
      - |
        act workflow_dispatch \
          --container-architecture linux/arm64 \
          --eventpath {{.PWD}}/event.json \
          --workflows .github/workflows/hello-world.yaml \
          --cache-server-path ~/.cache/act
