apiVersion: v1
kind: Service
metadata:
  name: api-node
  namespace: staging
  labels:
    app: api-node
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: api-node
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  sessionAffinity: None
