apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services-production
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - service: api-golang
          - service: api-node
          - service: client-react
          - service: load-generator-python

  template:
    metadata:
      name: '{{.service}}-production'
      labels:
        service: '{{.service}}'
        environment: production
    spec:
      project: production
      source:
        repoURL: https://github.com/tyler0ps/generic-gha.git
        targetRevision: main
        path: 'deploy/kubernetes/overlays/production/{{.service}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: production
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
