apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../../base/api-node

patchesStrategicMerge:
  - patches.yaml

commonLabels:
  environment: staging

images:
  - name: api-node-image
    newName: <ECR_ACCOUNT_ID>.dkr.ecr.ap-southeast-1.amazonaws.com/generic-gha/api-node
    newTag: 1.1.2-0034-gc7b8631
